name: floreria_encanto2
description: "Aplicaci칩n de Florer칤a Encanto"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.2       # 游늷 Para guardar fotos de perfil

  # Google Maps
  google_maps_flutter: ^2.6.1

  # Imagenes y c치mara
  image_picker: ^1.1.2             # 游늷 Para subir im치genes desde galer칤a o c치mara

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1   # 游늷 칈cono de app

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/rosas.jpg
    - assets/tulipanes.jpg
    - assets/lirios.jpg
    - assets/girasol.jpg
