name: floreria_encanto2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.0
  google_maps_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/rosas.jpg
    - assets/tulipanes.jpg
    - assets/lirios.jpg
    - assets/girasol.jpg
